# -*- coding: utf-8 -*-
"""Correlacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bA572ljCu-hIqzMUYoOuKS9rAwLP5LKg

#Bibliotecas
"""

#importação de bibliotecas

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from scipy.stats import normaltest
from scipy import stats

dados = pd.read_excel("/content/dataframe_pesquisa.xlsx")

dados

"""#Teste de Normalidade - Relacionamento com Líderes

"""

plt.figure(figsize=(10,7), dpi= 80)
sns.distplot(dados['Relac. Líder'], color="dodgerblue", label="Compact",)

plt.show()

alpha = 0.05
k2, p = normaltest(dados['Relac. Líder'])

#Hipotese nula: Os dados seguem distribuição normal
#Hipotese alternativa: Os dados não seguem distribuição normal

if p < alpha:
    print("A Hipótese Nula pode ser rejeitada")
else:
    print("A hipótese nula não pode ser rejeitada")

"""# Teste de Normaliade - Estresse"""

plt.figure(figsize=(10,7), dpi= 80)
sns.distplot(dados['Estresse'], color="dodgerblue", label="Compact",)

plt.show()

alpha = 0.05
k2, p = normaltest(dados['Estresse'])

#Hipotese nula: Os dados seguem distribuição normal
#Hipotese alternativa: Os dados não seguem distribuição normal

if p < alpha:
    print("A Hipótese Nula pode ser rejeitada")
else:
    print("A hipótese nula não pode ser rejeitada")

"""# Correlação

## Gráfico de Dispersão
"""

plt.figure(figsize=(10,7), dpi= 80)
sns.scatterplot(dados['Relac. Líder'],dados['Estresse'])
plt.show()

"""## Diagrama de Caixa"""

plt.figure(figsize=(10,7), dpi= 80)
array = (dados['Relac. Líder'], dados['Estresse'])
plt.boxplot(array)
plt.show()

"""## Teste de Correlação

"""

stats.spearmanr(dados['Relac. Líder'],dados['Estresse'])